container:
  image: cirrusci/flutter:latest

analysis_task:
  pub_cache:
    folder: ~/.pub-cache
  analysis_script: |
    flutter pub get
    flutter analyze

test_task:
  env:
    LD_LIBRARY_PATH: .
  pub_cache:
    folder: ~/.pub-cache
  install_isar_script: |
    core_version=`cat .isar_version`
    github="https://github.com/isar/isar-core/releases/download/${core_version}"
    curl "${github}/libisar_linux_x64.so" -o ./libisar.so --create-dirs -L
  # test_script: flutter test --machine > report.json
  test_script: |
    flutter pub get
    flutter test --reporter json | tee report.json
  always:
    report_artifacts:
      path: report.json
      format: flutter

build_apk_task:
  pub_cache:
    folder: ~/.pub-cache
  build_apk_script: |
    flutter pub get
    flutter build apk
